[package]
name = "sirpent"
version = "0.1.0"
authors = ["Nathan van Doorn <nvd1234@gmail.com>", "Michael Mokrysz <hi@46b.it>"]

[dependencies]
ansi_term = "0.8.0"
uuid = { version = "0.2", features = ["v4"] }
rand = "0.3.*"
rustc-serialize = "0.3.19"

[dev-dependencies]
quickcheck = "0.2.*"
