[package]
name = "sirpent"
version = "0.1.0"
authors = ["Nathan van Doorn <nvd1234@gmail.com>", "Michael Mokrysz <hi@46b.it>"]

[features]
default = ["hexagon"]
square = []
hexagon = []
triangle = []

[dependencies]
futures = "*"
tokio-core = "*"
tokio-timer = "*"
log = "*"
env_logger = "*"
ansi_term = "*"
uuid = { version = "0.4", features = ["v4", "serde"] }
rand = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"

[dev-dependencies]
quickcheck = "0.2.*"
