[package]
name = "sirpent"
version = "0.1.0"
authors = ["Nathan van Doorn <nvd1234@gmail.com>", "Michael Mokrysz <hi@46b.it>"]

[dependencies]
ansi_term = "0.8.0"
uuid = { version = "0.3", features = ["v4", "serde"] }
rand = "0.3.*"
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"

[dev-dependencies]
quickcheck = "0.2.*"
