[package]
name = "sirpent"
version = "0.1.0"
authors = ["Nathan van Doorn <nvd1234@gmail.com>", "Michael Mokrysz <hi@46b.it>"]

[features]
default = ["hexagon"]
square = []
hexagon = []
triangle = []

[dependencies]
ansi_term = "0.9"
uuid = { version = "0.3", features = ["v4", "serde"] }
rand = "0.3"
rayon = "0.5"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"

[dev-dependencies]
quickcheck = "0.2.*"
